2024-04-17 04:43:27,109 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 04:44:27,374 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 04:44:28,063 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 04:44:50,226 INFO: 유저 ID: <User ccrc@khu.ac.kr> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-17 04:44:50,229 INFO: Model: <Model 1>, Dataset: <Dataset 1> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-17 04:44:50,286 INFO: 프로젝트 생성 성공: Project ID 1 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
2024-04-17 04:44:50,385 INFO: 수정된 파일: {'id': 1, 'model': 1, 'dataset': 1, 'hyperparameters': {'learningRate': 0.1, 'batchSize': 32, 'epochs': 2, 'optimizer': 1, 'lossFunction': 1}, 'nodes': ['13.124.158.135', '15.165.105.49'], 'status': [['16', '0.4084745762730102', '0.25', '48220954624', '215162011648', '20', '9.509', '0', None, '66583072768', '233946071040', 'Tesla T4,1'], ['1', '4.122033898316135', '87', '51018944512', '110962356224', '37', '11.052', '0', None, '67422306304', '130922102784', 'Tesla T4,1'], ['16', '0.6527542372893214', '0.25', '46647431168', '214230040576', '23', '9.322', '0', None, '66583064576', '233946071040', 'Tesla T4,1'], ['16', '0.10237218730327902', '0', '58732580864', '123309322240', None, None, None, None, '66209673216', '130911944704', None]]} [in D:\develop\vue-flask-dashboard\backend\app\routes.py:116]
2024-04-17 04:44:55,794 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:356]
2024-04-17 04:44:56,797 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:356]
2024-04-17 04:44:57,791 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:356]
2024-04-17 04:44:58,776 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:356]
2024-04-17 04:49:17,859 INFO: 유저 ID: <User ccrc@khu.ac.kr> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-17 04:49:17,860 INFO: Model: <Model 1>, Dataset: <Dataset 1> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-17 04:49:17,879 INFO: 프로젝트 생성 성공: Project ID 2 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
2024-04-17 04:49:17,969 INFO: 수정된 파일: {'id': 2, 'model': 1, 'dataset': 1, 'hyperparameters': {'learningRate': 0.1, 'batchSize': 32, 'epochs': 10, 'optimizer': 1, 'lossFunction': 1}, 'nodes': ['13.124.158.135', '15.165.105.49'], 'status': [['16', '0.2726694915253125', '0', '48207851520', '215161040896', '19', '9.902', '0', None, '66583072768', '233946071040', 'Tesla T4,1'], ['1', '3.1220338982924645', '4', '51016105984', '110961893376', '32', '9.264', '0', None, '67422306304', '130922102784', 'Tesla T4,1'], ['16', '0.8207627118629879', '0', '46624796672', '214228090880', '23', '9.424', '0', None, '66583064576', '233946071040', 'Tesla T4,1'], ['16', '0.7893563794307945', '0', '58734505984', '123309318144', None, None, None, None, '66209673216', '130911944704', None]]} [in D:\develop\vue-flask-dashboard\backend\app\routes.py:116]
2024-04-17 04:49:23,376 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:356]
2024-04-17 04:49:24,382 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:356]
2024-04-17 04:49:25,374 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:356]
2024-04-17 04:49:26,374 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:356]
2024-04-17 04:49:27,377 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:356]
2024-04-17 04:49:28,382 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:356]
2024-04-17 04:49:29,389 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:356]
2024-04-17 04:49:30,380 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:356]
2024-04-17 04:49:31,376 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:356]
2024-04-17 04:49:32,395 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:356]
2024-04-17 04:49:33,380 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:356]
2024-04-17 04:53:38,314 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 04:54:10,652 INFO: 유저 ID: <User ccrc@khu.ac.kr> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-17 04:54:10,654 INFO: Model: <Model 1>, Dataset: <Dataset 1> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-17 04:54:10,700 INFO: 프로젝트 생성 성공: Project ID 3 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
2024-04-17 04:54:10,793 INFO: 수정된 파일: {'id': 3, 'model': 1, 'dataset': 1, 'hyperparameters': {'learningRate': 0.1, 'batchSize': 32, 'epochs': 10, 'optimizer': 1, 'lossFunction': 1}, 'nodes': ['13.124.158.135', '15.165.105.49'], 'status': [['16', '0.3616525423693395', '0.375', '48236933120', '215159959552', '19', '9.611', '0', None, '66583072768', '233946071040', 'Tesla T4,1'], ['1', '3.9627118644075754', '6', '51070275584', '110961356800', '30', '11.052', '0', None, '67422306304', '130922102784', 'Tesla T4,1'], ['16', '0.961652542374436', '0.375', '46648836096', '214226006016', '23', '9.417', '0', None, '66583064576', '233946071040', 'Tesla T4,1'], ['16', '2.8786961989680115', '0.125', '58732314624', '123309314048', None, None, None, None, '66209673216', '130911944704', None]]} [in D:\develop\vue-flask-dashboard\backend\app\routes.py:116]
2024-04-17 04:54:16,123 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-17 04:54:17,133 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-17 04:54:18,125 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-17 04:54:19,143 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-17 04:54:20,142 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-17 04:54:21,125 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-17 04:54:22,149 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-17 04:54:23,151 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-17 04:54:24,139 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:353]
2024-04-17 04:55:15,818 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
