2024-04-17 04:31:39,021 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 04:31:39,758 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 04:31:52,767 INFO: 유저 ID: <User ccrc@khu.ac.kr> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-17 04:31:52,770 INFO: Model: <Model 1>, Dataset: <Dataset 1> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-17 04:31:52,818 INFO: 프로젝트 생성 성공: Project ID 1 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
2024-04-17 04:31:52,914 INFO: 수정된 파일: {'id': 1, 'model': 1, 'dataset': 1, 'hyperparameters': {'learningRate': 0.1, 'batchSize': 32, 'epochs': 10, 'optimizer': 1, 'lossFunction': 1}, 'nodes': ['13.124.158.135', '15.165.105.49'], 'status': [['16', '0.3307203389790514', '0', '48222343168', '215164895232', '19', '9.407', '0', None, '66583072768', '233946071040', 'Tesla T4,1'], ['1', '3.396610169497838', '0', '51074428928', '110963761152', '30', '9.562', '0', None, '67422306304', '130922102784', 'Tesla T4,1'], ['16', '3.018644067796228', '1.7500000000000002', '46675427328', '214235652096', '23', '9.326', '0', None, '66583064576', '233946071040', 'Tesla T4,1'], ['16', '17.08093220338923', '3.5624999999999996', '58732085248', '123309330432', None, None, None, None, '66209673216', '130911944704', None]]} [in D:\develop\vue-flask-dashboard\backend\app\routes.py:116]
2024-04-17 04:31:58,082 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:31:59,086 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:08,812 INFO: 유저 ID: <User ccrc@khu.ac.kr> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-17 04:32:08,813 INFO: Model: <Model 1>, Dataset: <Dataset 1> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-17 04:32:08,832 INFO: 프로젝트 생성 성공: Project ID 2 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
2024-04-17 04:32:08,935 INFO: 수정된 파일: {'id': 2, 'model': 1, 'dataset': 1, 'hyperparameters': {'learningRate': 0.1, 'batchSize': 32, 'epochs': 10, 'optimizer': 1, 'lossFunction': 1}, 'nodes': ['43.203.73.249', '34.64.157.92'], 'status': [['16', '0.3334745762746949', '0', '48219021312', '215164817408', '19', '10.197', '0', None, '66583072768', '233946071040', 'Tesla T4,1'], ['1', '3.406779661013004', '0', '51074428928', '110963728384', '30', '9.364', '0', None, '67422306304', '130922102784', 'Tesla T4,1'], ['16', '3.2434322033916163', '2.3125', '46181822464', '214235541504', '23', '9.326', '0', None, '66583064576', '233946071040', 'Tesla T4,1'], ['16', '17.88101105770229', '10.125', '58658955264', '123309326336', None, None, None, None, '66209673216', '130911944704', None]]} [in D:\develop\vue-flask-dashboard\backend\app\routes.py:116]
2024-04-17 04:32:13,316 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:14,307 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:15,318 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:16,300 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:17,317 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:18,304 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:18,404 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:18,695 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:19,134 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:19,664 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:20,689 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:21,049 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:21,714 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:22,323 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:24,198 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:25,200 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:26,203 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:32:27,193 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:35:30,472 INFO: 유저 ID: <User ccrc@khu.ac.kr> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-17 04:35:30,473 INFO: Model: <Model 1>, Dataset: <Dataset 1> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-17 04:35:30,494 INFO: 프로젝트 생성 성공: Project ID 3 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
2024-04-17 04:35:30,582 INFO: 수정된 파일: {'id': 3, 'model': 1, 'dataset': 1, 'hyperparameters': {'learningRate': 10, 'batchSize': 32, 'epochs': 10, 'optimizer': 1, 'lossFunction': 1}, 'nodes': ['13.124.158.135', '15.165.105.49'], 'status': [['16', '0.793855932200338', '0.0625', '48212877312', '215164084224', '19', '9.509', '0', None, '66583072768', '233946071040', 'Tesla T4,1'], ['1', '5.416949152536066', '0', '50597298176', '110963359744', '42', '27.632', '0', None, '67422306304', '130922102784', 'Tesla T4,1'], ['16', '1.4879237288119462', '3.6249999999999996', '46651351040', '214234103808', '23', '11.885', '0', None, '66583064576', '233946071040', 'Tesla T4,1'], ['16', '2.6892190561437213', '0.9375', '58656112640', '123309326336', None, None, None, None, '66209673216', '130911944704', None]]} [in D:\develop\vue-flask-dashboard\backend\app\routes.py:116]
2024-04-17 04:35:35,584 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:35:44,537 INFO: 유저 ID: <User ccrc@khu.ac.kr> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-17 04:35:44,539 INFO: Model: <Model 1>, Dataset: <Dataset 1> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-17 04:35:44,555 INFO: 프로젝트 생성 성공: Project ID 4 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
2024-04-17 04:35:44,643 INFO: 수정된 파일: {'id': 4, 'model': 1, 'dataset': 1, 'hyperparameters': {'learningRate': 0.1, 'batchSize': 32, 'epochs': 10, 'optimizer': 1, 'lossFunction': 1}, 'nodes': ['43.203.73.249', '34.64.157.92'], 'status': [['16', '0.7847457627114252', '0.0625', '48214253568', '215164030976', '19', '9.509', '0', None, '66583072768', '233946071040', 'Tesla T4,1'], ['1', '5.369491525412684', '0', '50597298176', '110963339264', '44', '27.731', '0', None, '67422306304', '130922102784', 'Tesla T4,1'], ['16', '1.4692796610152326', '2.8125', '46449135616', '214233993216', '23', '11.885', '0', None, '66583064576', '233946071040', 'Tesla T4,1'], ['16', '2.68858346723434', '0.75', '58655596544', '123309326336', None, None, None, None, '66209673216', '130911944704', None]]} [in D:\develop\vue-flask-dashboard\backend\app\routes.py:116]
2024-04-17 04:35:49,564 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:35:50,565 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:35:58,293 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:40:59,748 INFO: 유저 ID: <User ccrc@khu.ac.kr> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
