2024-04-17 04:26:38,907 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 04:26:39,612 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-17 04:27:19,520 INFO: 유저 ID: <User ccrc@khu.ac.kr> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-17 04:27:19,523 INFO: Model: <Model 1>, Dataset: <Dataset 1> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-17 04:27:19,578 INFO: 프로젝트 생성 성공: Project ID 1 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
2024-04-17 04:27:19,672 INFO: 수정된 파일: {'id': 1, 'model': 1, 'dataset': 1, 'hyperparameters': {'learningRate': 0.05, 'batchSize': 64, 'epochs': 30, 'optimizer': 1, 'lossFunction': 1}, 'nodes': ['13.124.158.135', '15.165.105.49'], 'status': [['16', '0.18495762711701058', '0', '48239554560', '215165886464', '19', '9.315', '0', None, '66583072768', '233946071040', 'Tesla T4,1'], ['1', '2.4711864406708695', '0', '51077009408', '110964236288', '30', '9.463', '0', None, '67422306304', '130922102784', 'Tesla T4,1'], ['16', '0.2597457627120492', '0.0625', '46696292352', '214237638656', '23', '11.195', '0', None, '66583064576', '233946071040', 'Tesla T4,1'], ['16', '0.016737288135160178', '0.1875', '58716274688', '123309338624', None, None, None, None, '66209673216', '130911944704', None]]} [in D:\develop\vue-flask-dashboard\backend\app\routes.py:116]
2024-04-17 04:27:25,218 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:26,232 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:27,235 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:28,219 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:29,233 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:30,238 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:31,242 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:32,227 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:33,239 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:34,226 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:35,221 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:36,247 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:37,223 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:38,232 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:39,236 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:40,224 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:41,222 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:42,240 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:43,223 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:44,224 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:45,244 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:46,222 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:27:47,229 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:28:00,591 INFO: 유저 ID: <User ccrc@khu.ac.kr> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-17 04:28:00,593 INFO: Model: <Model 1>, Dataset: <Dataset 1> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
2024-04-17 04:28:00,609 INFO: 프로젝트 생성 성공: Project ID 2 [in D:\develop\vue-flask-dashboard\backend\app\routes.py:85]
2024-04-17 04:28:00,701 INFO: 수정된 파일: {'id': 2, 'model': 1, 'dataset': 1, 'hyperparameters': {'learningRate': 0.06, 'batchSize': 64, 'epochs': 50, 'optimizer': 1, 'lossFunction': 1}, 'nodes': ['13.124.158.135', '15.165.105.49'], 'status': [['16', '0.199788135596779', '0', '48236187648', '215165739008', '19', '9.705', '0', None, '66583072768', '233946071040', 'Tesla T4,1'], ['1', '2.5830508474560476', '0', '51075461120', '110964166656', '30', '10.556', '0', None, '67422306304', '130922102784', 'Tesla T4,1'], ['16', '1.0093220338961428', '2.875', '46694092800', '214237347840', '24', '25.809', '0', None, '66583064576', '233946071040', 'Tesla T4,1'], ['16', '5.933157853703996', '30.25', '58727403520', '123309334528', None, None, None, None, '66209673216', '130911944704', None]]} [in D:\develop\vue-flask-dashboard\backend\app\routes.py:116]
2024-04-17 04:28:06,126 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:28:06,831 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:28:07,833 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:28:08,847 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:28:09,840 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:28:10,375 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:28:11,394 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:28:12,390 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:28:13,717 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:28:14,725 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:28:15,731 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:28:16,755 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:28:17,747 ERROR: Unhandled exception: cannot access local variable 'project_node_names' where it is not associated with a value [in D:\develop\vue-flask-dashboard\backend\app\routes.py:351]
2024-04-17 04:31:27,160 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
